### PR TITLE
CipherText

### PR DESCRIPTION
**Pull request by GrayHatter**
@iphydf

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/hstox/42)

### CODE REVIEW

**Comment by nbraud** [comment]
*[test/toxcore/methods.h, line 22 \[r1\]](https://reviewable.io:443/reviews/toktok/hstox/42#-KNqZCBr45F_osCG7bwk:-KNqZCBsaUyr4l8wJJ_N:1379433092) ([raw file](https://github.com/toktok/hstox/blob/f4bebdb9b5340218053bcbcaa4fdd870db4e1c92/test/toxcore/methods.h#L22)):*
> ```objc
>         "%s:%d: Type of `" #ARG "' expected to be %s, but was %s", \
>         __FILE__, __LINE__, type_name (TYPE), type_name ((ARG).type)); \
> } while (0)
> ```

Looks good, but why is this crammed in the same commit?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/42)*

**Comment by GrayHatter** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[test/toxcore/methods.h, line 22 \[r1\]](https://reviewable.io:443/reviews/toktok/hstox/42#-KNqZCBr45F_osCG7bwk:-KNxBxty0UxmBLmDXwVy:-1129722433) ([raw file](https://github.com/toktok/hstox/blob/f4bebdb9b5340218053bcbcaa4fdd870db4e1c92/test/toxcore/methods.h#L22)):*
<details><summary><i>Previously, nbraud (Nicolas Braud-Santoni) wrote…</i></summary>
> Looks good, but why is this crammed in the same commit?
</details>
IIRC this got merged from another PR, once this is closer to merge I'll rebase on master, and with any luck this will already be there. If it's not would you rather I rip this out?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/42)*

**Comment by GrayHatter** [comment]
@iphydf rebased, PTAL

**Comment by iphydf** [comment]
Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[test/toxcore/binary_decode.c, line 86 \[r2\]](https://reviewable.io:443/reviews/toktok/hstox/42#-KNxZ0phXZEtUbIy-Gk_:-KNxZ0phXZEtUbIy-Gka:195213199) ([raw file](https://github.com/toktok/hstox/blob/23213b4cc2c3fa084f081c5c80c1c0ceda7d1e64/test/toxcore/binary_decode.c#L86)):*
> ```C
>       msgpack_pack_bin_body(res, &node.public_key, crypto_box_PUBLICKEYBYTES);
>     } else {
> ```

Why is there a new newline here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/42)*

**Comment by GrayHatter** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[test/toxcore/binary_decode.c, line 86 \[r2\]](https://reviewable.io:443/reviews/toktok/hstox/42#-KNxZ0phXZEtUbIy-Gk_:-KNxeNjtF03-212ky2rj:-499601445) ([raw file](https://github.com/toktok/hstox/blob/23213b4cc2c3fa084f081c5c80c1c0ceda7d1e64/test/toxcore/binary_decode.c#L86)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> Why is there a new newline here?
</details>
Will be fixed when clang-format is merged

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/42)*

**Comment by nbraud** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[test/toxcore/methods.h, line 22 \[r1\]](https://reviewable.io:443/reviews/toktok/hstox/42#-KNqZCBr45F_osCG7bwk:-KNy0UDv4stSUYaWUyeu:5173665) ([raw file](https://github.com/toktok/hstox/blob/f4bebdb9b5340218053bcbcaa4fdd870db4e1c92/test/toxcore/methods.h#L22)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> IIRC this got merged from another PR, once this is closer to merge I'll rebase on master, and with any luck this will already be there. If it's not would you rather I rip this out?
</details>
OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/42)*

**Pull request closed without merging**
