### PR TITLE
Binary Encode/Decode Port Number

### PR DESCRIPTION
**Pull request by GrayHatter**
~~Needs #48~~

~~Then it's~~ ready to go now.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/hstox/54)

### CODE REVIEW

**Comment by iphydf** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/toxcore/binary_encode.c, line 134 \[r1\]](https://reviewable.io:443/reviews/toktok/hstox/54#-KO-V8UJJM00kvYJnChz:-KO-V8UJJM00kvYJnCi-:-1478556996) ([raw file](https://github.com/toktok/hstox/blob/61c4f9b041d9c3edad556073b750d72e7cf5ced0/test/toxcore/binary_encode.c#L134)):*
> ```C
> 
>   SUCCESS {
>     if (args <= UINT16_MAX) {
> ```

Make this a CHECK and make the SUCCESS block total (never returning nil). Reason: the test specification says uint16, so if this is not true, then the test runner has a bug.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/54)*

**Comment by GrayHatter** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/toxcore/binary_encode.c, line 134 \[r1\]](https://reviewable.io:443/reviews/toktok/hstox/54#-KO-V8UJJM00kvYJnChz:-KO-XumR08RlhkdSzm1y:-499146009) ([raw file](https://github.com/toktok/hstox/blob/61c4f9b041d9c3edad556073b750d72e7cf5ced0/test/toxcore/binary_encode.c#L134)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> Make this a CHECK and make the SUCCESS block total (never returning nil). Reason: the test specification says uint16, so if this is not true, then the test runner has a bug.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/54)*

**Comment by iphydf** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[test/toxcore/binary_decode.c, line 89 \[r2\]](https://reviewable.io:443/reviews/toktok/hstox/54#-KO00RI9ZJ_pyu_dtkSH:-KO00RI9ZJ_pyu_dtkSI:119255850) ([raw file](https://github.com/toktok/hstox/blob/986c05933df97a330169aff768bec0ac25bb8608/test/toxcore/binary_decode.c#L89)):*
> ```C
> 
> METHOD(bin, Binary_decode, PortNumber) {
>   CHECK_SIZE(args, 2);
> ```

If size != 2, return nil.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/54)*

**Comment by GrayHatter** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[test/toxcore/binary_decode.c, line 89 \[r2\]](https://reviewable.io:443/reviews/toktok/hstox/54#-KO00RI9ZJ_pyu_dtkSH:-KO1UQmCwPCGO95dH5rH:1610528777) ([raw file](https://github.com/toktok/hstox/blob/986c05933df97a330169aff768bec0ac25bb8608/test/toxcore/binary_decode.c#L89)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> If size != 2, return nil.
</details>
I thought about doing that, but there's no way to pass toxcore a port that's <2 without passing a null pointer instead of an IP_Port struct. (I still haven't read EVERY line of code in core so I might be missing something.)  So there's to reason to check this in toxcore. 

Also, ran this test about 20 times and never saw a failure do to this check. 

Do you still want me to check in SUCCESS{} ? or should I leave this macro?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/54)*

**Comment by GrayHatter** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/toxcore/binary_decode.c, line 89 \[r2\]](https://reviewable.io:443/reviews/toktok/hstox/54#-KO00RI9ZJ_pyu_dtkSH:-KO2CIH8CartB812v347:-499146009) ([raw file](https://github.com/toktok/hstox/blob/986c05933df97a330169aff768bec0ac25bb8608/test/toxcore/binary_decode.c#L89)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> I thought about doing that, but there's no way to pass toxcore a port that's <2 without passing a null pointer instead of an IP_Port struct. (I still haven't read EVERY line of code in core so I might be missing something.)  So there's to reason to check this in toxcore. 
> 
> Also, ran this test about 20 times and never saw a failure do to this check. 
> 
> Do you still want me to check in SUCCESS{} ? or should I leave this macro?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/54)*

**Comment by iphydf** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/54#-:-KO2DxGqmk2aEeOVJs1v:1417088721)*

**Pull request merged**
