### PR TITLE
Add AGPL-3 license.

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/toktok/hstox/28)

### CODE REVIEW

**Comment by zetok** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[licenses/gnu-agpl-v3.0.md, line 5 \[r1\]](https://reviewable.io:443/reviews/toktok/hstox/28#-KMGwowGx3uyhlguDtJP:-KMGwowGx3uyhlguDtJQ:1736116311) ([raw file](https://github.com/toktok/hstox/blob/27636b3731702cc83ee784b799691980d5432696/licenses/gnu-agpl-v3.0.md#L5)):*
> ```Markdown
> 
> _Version 3, 19 November 2007_
> _Copyright © 2007 Free Software Foundation, Inc. &lt;<http://fsf.org/>&gt;_
> ```

Formatting isn't preserved – it might be desirable to put version and copyright notice on separate lines.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/28)*

**Comment by GrayHatter** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[LICENSE.md, line 7 \[r1\]](https://reviewable.io:443/reviews/toktok/hstox/28#-KMGwQYZnYqicdLoLgrj:-KMGwQYZnYqicdLoLgrk:-817878473) ([raw file](https://github.com/toktok/hstox/blob/27636b3731702cc83ee784b799691980d5432696/LICENSE.md#L7)):*
> ```Markdown
> [Tox-Docs](https://github.com/Tox-Docs/Text/commit/8f77b8a7c935871eea48cc5abeef26dfa42a108a)
> repository are licensed under [MIT](licenses/mit.md). The parts that were not
> originally part of that repository are licensed under AGPLv3.
> ```

As this is plain text, do you want to add a comment similar to, "contributors also may maintain their original copyrights in addition"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/28)*

**Comment by zetok** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[LICENSE.md, line 7 \[r1\]](https://reviewable.io:443/reviews/toktok/hstox/28#-KMGwQYZnYqicdLoLgrj:-KMGyVImz7PgUXOV5MZZ:1270766063) ([raw file](https://github.com/toktok/hstox/blob/27636b3731702cc83ee784b799691980d5432696/LICENSE.md#L7)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> As this is plain text, do you want to add a comment similar to, "contributors also may maintain their original copyrights in addition"
</details>
Wouldn't that be redundant with CLA? It would be also irrelevant to everyone who is just interested on what terms they can use the work, and anyone willing to contribute will read CLA anyway.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/28)*

**Comment by GrayHatter** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[LICENSE.md, line 7 \[r1\]](https://reviewable.io:443/reviews/toktok/hstox/28#-KMGwQYZnYqicdLoLgrj:-KMGzQBykFZhoJXw9y1P:649480792) ([raw file](https://github.com/toktok/hstox/blob/27636b3731702cc83ee784b799691980d5432696/LICENSE.md#L7)):*
<details><summary><i>Previously, zetok wrote…</i></summary>
> Wouldn't that be redundant with CLA? It would be also irrelevant to everyone who is just interested on what terms they can use the work, and anyone willing to contribute will read CLA anyway.
</details>
OK
I'm okay with either. I only made the suggestion, as this was the first section I read before the CLA, and if I had seen something like that I wouldn't have read the whole CLA.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/28)*

**Comment by iphydf** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[LICENSE.md, line 7 \[r1\]](https://reviewable.io:443/reviews/toktok/hstox/28#-KMGwQYZnYqicdLoLgrj:-KMH3KGcMHwdnt54KAvX:-2141610606) ([raw file](https://github.com/toktok/hstox/blob/27636b3731702cc83ee784b799691980d5432696/LICENSE.md#L7)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> OK
> I'm okay with either. I only made the suggestion, as this was the first section I read before the CLA, and if I had seen something like that I wouldn't have read the whole CLA.
</details>
Added two lines about this in a wording that would be interesting to people who want to use the software. This basically says: we don't own copyright to all contributions.

---

*[licenses/gnu-agpl-v3.0.md, line 5 \[r1\]](https://reviewable.io:443/reviews/toktok/hstox/28#-KMGwowGx3uyhlguDtJP:-KMH3gxhSKIm8YRmn9Jk:-2017341429) ([raw file](https://github.com/toktok/hstox/blob/27636b3731702cc83ee784b799691980d5432696/licenses/gnu-agpl-v3.0.md#L5)):*
<details><summary><i>Previously, zetok wrote…</i></summary>
> Formatting isn't preserved – it might be desirable to put version and copyright notice on separate lines.
</details>
I pulled this file from https://github.com/IQAndreas/markdown-licenses/blob/master/gnu-agpl-v3.0.md but yes, true. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/28)*

**Comment by zetok** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/28)*

**Pull request merged**
