### PR TITLE
Reinstate monad/applicative law tests for Data.Result.

### PR DESCRIPTION
**Pull request by iphydf**
Also add some other small tests for various types.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/hstox/49)

### CODE REVIEW

**Comment by nbraud** [comment]
FYI, there are a couple of libraries that implement the typeclass laws, but IIRC they aren't in the standard library.
On the other hand, it's sane to just write ours in that case.

---

Reviewed 6 of 9 files at r1.
Review status: 6 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/testsuite/Data/ResultSpec.hs, line 14 \[r1\]](https://reviewable.io:443/reviews/toktok/hstox/49#-KO26FU2H7upAehoxJ8J:-KO26FU2H7upAehoxJ8K:1114126102) ([raw file](https://github.com/toktok/hstox/blob/48cac9a84ab2427fc5fc8d9ed67a44f884d5bc4d/src/testsuite/Data/ResultSpec.hs#L14)):*
> ```Haskell
> spec :: Spec
> spec = do
>   describe "Monad" $ do
> ```

Link to the [Monad laws](https://wiki.haskell.org/Monad_laws)?

---

*[src/testsuite/Data/ResultSpec.hs, line 24 \[r1\]](https://reviewable.io:443/reviews/toktok/hstox/49#-KO26Oj1TGZYrL-404uZ:-KO26Oj2qIZd85TJZ1no:-976980412) ([raw file](https://github.com/toktok/hstox/blob/48cac9a84ab2427fc5fc8d9ed67a44f884d5bc4d/src/testsuite/Data/ResultSpec.hs#L24)):*
> ```Haskell
>       property $ \m -> ((m `bind'` f) `bind'` g) `shouldBe` (m `bind'` (\x -> f x `bind'` g))
> 
>   describe "Applicative" $ do
> ```

Link to the [Control.Applicative documentation](https://hackage.haskell.org/package/base-4.9.0.0/docs/Control-Applicative.html)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/49#-:-KO26lnPSZdQAVuxXwsF:-362075313)*

**Comment by iphydf** [comment]
Can you point me at those libraries? Perhaps we can use them.

---

Review status: 5 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/testsuite/Data/ResultSpec.hs, line 14 \[r1\]](https://reviewable.io:443/reviews/toktok/hstox/49#-KO26FU2H7upAehoxJ8J:-KO2DjDpmPzDTM-idCN3:-499146009) ([raw file](https://github.com/toktok/hstox/blob/48cac9a84ab2427fc5fc8d9ed67a44f884d5bc4d/src/testsuite/Data/ResultSpec.hs#L14)):*
<details><summary><i>Previously, nbraud (Nicolas Braud-Santoni) wrote…</i></summary>
> Link to the [Monad laws](https://wiki.haskell.org/Monad_laws)?
</details>
Done.

---

*[src/testsuite/Data/ResultSpec.hs, line 24 \[r1\]](https://reviewable.io:443/reviews/toktok/hstox/49#-KO26Oj1TGZYrL-404uZ:-KO2Dk2joqr9mCA4O4J2:-499146009) ([raw file](https://github.com/toktok/hstox/blob/48cac9a84ab2427fc5fc8d9ed67a44f884d5bc4d/src/testsuite/Data/ResultSpec.hs#L24)):*
<details><summary><i>Previously, nbraud (Nicolas Braud-Santoni) wrote…</i></summary>
> Link to the [Control.Applicative documentation](https://hackage.haskell.org/package/base-4.9.0.0/docs/Control-Applicative.html)?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/49#-:-KO2DfvjE3Kh6OYuC1Cg:482784218)*

**Comment by nbraud** [comment]
There is [ClassLaws](https://hackage.haskell.org/package/ClassLaws) and [QuickCheck-laws](https://github.com/AustinRochford/quickcheck-laws/blob/master/src/Laws.lhs) at least.
However, I didn't notice that they do now have the laws for `Applicative`.

I guess our options are to either pick one such library and extend it (and submit changes back to repositories that have seen no change in years), or write our own.

---

Reviewed 1 of 3 files at r3.
Review status: 6 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/49#-:-KO5mkodlb4jz2tM_epN:545769318)*

**Comment by nbraud** [comment]
Reviewed 2 of 9 files at r1, 2 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/49)*

**Comment by iphydf** [comment]
@nbraud I'll keep the own implementation for now. If this is good to go, please LGTM to sign off so I can merge it.

**Comment by nbraud** [comment]
Is it good to go
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/49#-:-KOAE1DA42cyrSkI8ioM:-126896360)*

**Comment by iphydf** [comment]
@nbraud can you LGTM again? There are only whitespace changes made by a new version of stylish-haskell.

**Comment by nbraud** [comment]
:lgtm:

---

Review status: 9 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/49#-:-KP0U7EgUFpbYIz4nv8I:bnfp4nl)*

**Pull request merged**
