### PR TITLE
Added Box [ encrypt, decrypt ] and CombinedKey [ precompute ] tests

### PR DESCRIPTION
**Pull request by piling**
This change is [Reviewable](https://reviewable.io/reviews/toktok/hstox/14)

### CODE REVIEW

**Comment by piling** [comment]
:+1:

**Comment by iphydf** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[test/toxcore/methods.c, line 21 \[r2\]](https://reviewable.io:443/reviews/toktok/hstox/14#-KMJNPBEx8mjAM5PerNf:-KMJNPBEx8mjAM5PerNg:595226324) ([raw file](https://github.com/toktok/hstox/blob/7f4537e26baff6c39de40298b9c5dcb4d3755751/test/toxcore/methods.c#L21)):*
> ```C
>   CHECK (args.ptr[1].via.bin.size == crypto_box_NONCEBYTES);
> 
>   uint8_t combined_key[crypto_box_BEFORENMBYTES];
> ```

Instead of copying combined_key, nonce, and plain_text to temporary arrays, you can just pass them into encrypt_data_symmetric directly. You'll need to cast them, because they are `char*` instead of `uint8_t*`.

---

*[test/toxcore/methods.c, line 24 \[r2\]](https://reviewable.io:443/reviews/toktok/hstox/14#-KMJNiPIuI86nBRRaZvj:-KMJNiPJejA_gNkSsg_f:-769778346) ([raw file](https://github.com/toktok/hstox/blob/7f4537e26baff6c39de40298b9c5dcb4d3755751/test/toxcore/methods.c#L24)):*
> ```C
>   uint8_t nonce[crypto_box_NONCEBYTES];
>   uint8_t plain_text[args.ptr[2].via.bin.size];
>   uint8_t cipher_text[sizeof (plain_text) + crypto_box_MACBYTES];
> ```

Style: write `sizeof plain_text` when plain_text is a variable. `sizeof (type)` is used for types.

---

*[test/toxcore/methods.c, line 32 \[r2\]](https://reviewable.io:443/reviews/toktok/hstox/14#-KMJNtGuAdBV9q7YeNq-:-KMJNtGuAdBV9q7YeNq0:-206593565) ([raw file](https://github.com/toktok/hstox/blob/7f4537e26baff6c39de40298b9c5dcb4d3755751/test/toxcore/methods.c#L32)):*
> ```C
>   int len = encrypt_data_symmetric (combined_key, nonce, plain_text, sizeof plain_text, cipher_text);
>   if (len < 0)
>       return "An error occured while encryption process.";
> ```

Error messages like this (as opposed to log messages) should not be capitalised and should not have a "." at the end. The reason is that they should be written to be composable. Think of a chain of errors that can be connected using commas. For example, you write "an encryption error occurred" as your error message, and then a caller at a higher level can do: `"the test failed, because " + error`, and yet another higher level says `"won't deploy to production, because " + error`, and you end up with `"won't deploy to production, because the test failed, because an encryption error occurred"`.

---

*[test/toxcore/methods.c, line 60 \[r2\]](https://reviewable.io:443/reviews/toktok/hstox/14#-KMJOhNU3ezv7inwyMgs:-KMJOhNV2Uh70ta-5MZd:155605473) ([raw file](https://github.com/toktok/hstox/blob/7f4537e26baff6c39de40298b9c5dcb4d3755751/test/toxcore/methods.c#L60)):*
> ```C
>   memcpy (cipher_text, args.ptr[2].via.bin.ptr, sizeof cipher_text);
> 
>   decrypt_data_symmetric (combined_key, nonce, cipher_text, sizeof cipher_text, plain_text);
> ```

Add return value check.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/14)*

**Comment by iphydf** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[test/toxcore/methods.c, line 28 \[r3\]](https://reviewable.io:443/reviews/toktok/hstox/14#-KMJ_DyXEZEFIIq2R-oc:-KMJ_DyXEZEFIIq2R-od:-1025258514) ([raw file](https://github.com/toktok/hstox/blob/90f9a00d504cbc4308411e66ca3d405a1aad43e8/test/toxcore/methods.c#L28)):*
> ```C
>                                     args.ptr[2].via.bin.size, cipher_text);
>   if (len < 0)
>       return "an error occured while encryption process";
> ```

Indentation is 2 spaces. Remove two leading spaces here.

---

*[test/toxcore/methods.c, line 74 \[r3\]](https://reviewable.io:443/reviews/toktok/hstox/14#-KMJ_Knz4Qp4RPbxoynF:-KMJ_Ko-Y8YOI-rMvjpn:1593080291) ([raw file](https://github.com/toktok/hstox/blob/90f9a00d504cbc4308411e66ca3d405a1aad43e8/test/toxcore/methods.c#L74)):*
> ```C
> 
>     uint8_t secret_key[crypto_box_SECRETKEYBYTES];
>     uint8_t public_key[crypto_box_PUBLICKEYBYTES];
> ```

No need for these temporaries.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/14)*

**Comment by piling** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[test/toxcore/methods.c, line 21 \[r2\]](https://reviewable.io:443/reviews/toktok/hstox/14#-KMJNPBEx8mjAM5PerNf:-KMJZusUVrqVEAQ5emy6:-499146009) ([raw file](https://github.com/toktok/hstox/blob/7f4537e26baff6c39de40298b9c5dcb4d3755751/test/toxcore/methods.c#L21)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> Instead of copying combined_key, nonce, and plain_text to temporary arrays, you can just pass them into encrypt_data_symmetric directly. You'll need to cast them, because they are `char*` instead of `uint8_t*`.
</details>
Done.

---

*[test/toxcore/methods.c, line 24 \[r2\]](https://reviewable.io:443/reviews/toktok/hstox/14#-KMJNiPIuI86nBRRaZvj:-KMJ_5nhqnrbckRym4le:-499146009) ([raw file](https://github.com/toktok/hstox/blob/7f4537e26baff6c39de40298b9c5dcb4d3755751/test/toxcore/methods.c#L24)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> Style: write `sizeof plain_text` when plain_text is a variable. `sizeof (type)` is used for types.
</details>
Done.

---

*[test/toxcore/methods.c, line 60 \[r2\]](https://reviewable.io:443/reviews/toktok/hstox/14#-KMJOhNU3ezv7inwyMgs:-KMJ_7hL7AbDA2ez6Y1C:-499146009) ([raw file](https://github.com/toktok/hstox/blob/7f4537e26baff6c39de40298b9c5dcb4d3755751/test/toxcore/methods.c#L60)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> Add return value check.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/14)*

**Comment by piling** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/toxcore/methods.c, line 28 \[r3\]](https://reviewable.io:443/reviews/toktok/hstox/14#-KMJ_DyXEZEFIIq2R-oc:-KMJjpAfcblHb0fikHop:-499146009) ([raw file](https://github.com/toktok/hstox/blob/90f9a00d504cbc4308411e66ca3d405a1aad43e8/test/toxcore/methods.c#L28)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> Indentation is 2 spaces. Remove two leading spaces here.
</details>
Done.

---

*[test/toxcore/methods.c, line 74 \[r3\]](https://reviewable.io:443/reviews/toktok/hstox/14#-KMJ_Knz4Qp4RPbxoynF:-KMJjnl_DnRRXLfrrsdk:-499146009) ([raw file](https://github.com/toktok/hstox/blob/90f9a00d504cbc4308411e66ca3d405a1aad43e8/test/toxcore/methods.c#L74)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> No need for these temporaries.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/14)*

**Comment by iphydf** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[test/toxcore/methods.c, line 68 \[r4\]](https://reviewable.io:443/reviews/toktok/hstox/14#-KMJliw2Xt919OAWkwwF:-KMJliw2Xt919OAWkwwG:113436418) ([raw file](https://github.com/toktok/hstox/blob/24aae626aac9ed66ad8f211579c5cef948d7b8eb/test/toxcore/methods.c#L68)):*
> ```C
>     CHECK (args.size == 2);
>     CHECK (args.ptr[1].type == MSGPACK_OBJECT_BIN);
>     CHECK (args.ptr[1].via.bin.size == crypto_box_SECRETKEYBYTES);
> ```

1? I think you meant 0.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/14)*

**Comment by iphydf** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[test/toxcore/methods.c, line 57 \[r4\]](https://reviewable.io:443/reviews/toktok/hstox/14#-KMJlpyJcgfF-FCiVYek:-KMJlpyJcgfF-FCiVYel:-715897096) ([raw file](https://github.com/toktok/hstox/blob/24aae626aac9ed66ad8f211579c5cef948d7b8eb/test/toxcore/methods.c#L57)):*
> ```C
> 
>   SUCCESS {
>     msgpack_pack_bin(res, sizeof plain_text);
> ```

Space before `(`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/14)*

**Comment by iphydf** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[test/toxcore/methods.c, line 79 \[r4\]](https://reviewable.io:443/reviews/toktok/hstox/14#-KMJm0h3oASjfa0iUU3b:-KMJm0h4RSvqmHVwkUB1:2084364501) ([raw file](https://github.com/toktok/hstox/blob/24aae626aac9ed66ad8f211579c5cef948d7b8eb/test/toxcore/methods.c#L79)):*
> ```C
> 
>     SUCCESS {
>         msgpack_pack_bin (res, sizeof combined_key);
> ```

2 space indent.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/14)*

**Comment by iphydf** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[test/toxcore/methods.c, line 182 \[r4\]](https://reviewable.io:443/reviews/toktok/hstox/14#-KMJmWtHRnf9T_yb-DRB:-KMJmWtHRnf9T_yb-DRC:1402369297) ([raw file](https://github.com/toktok/hstox/blob/24aae626aac9ed66ad8f211579c5cef948d7b8eb/test/toxcore/methods.c#L182)):*
> ```C
>   return unimplemented;
> }
> ```

Why is there an additional empty line here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/14)*

**Comment by piling** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[test/toxcore/methods.c, line 57 \[r4\]](https://reviewable.io:443/reviews/toktok/hstox/14#-KMJlpyJcgfF-FCiVYek:-KMJoC4Ub3-bEdF-63tD:-499146009) ([raw file](https://github.com/toktok/hstox/blob/24aae626aac9ed66ad8f211579c5cef948d7b8eb/test/toxcore/methods.c#L57)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> Space before `(`.
</details>
Done.

---

*[test/toxcore/methods.c, line 68 \[r4\]](https://reviewable.io:443/reviews/toktok/hstox/14#-KMJliw2Xt919OAWkwwF:-KMJoAeLMozzjPsoQ4Ce:-499146009) ([raw file](https://github.com/toktok/hstox/blob/24aae626aac9ed66ad8f211579c5cef948d7b8eb/test/toxcore/methods.c#L68)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> 1? I think you meant 0.
</details>
Done.

---

*[test/toxcore/methods.c, line 79 \[r4\]](https://reviewable.io:443/reviews/toktok/hstox/14#-KMJm0h3oASjfa0iUU3b:-KMJo5V20ys2StGpHKIS:-499146009) ([raw file](https://github.com/toktok/hstox/blob/24aae626aac9ed66ad8f211579c5cef948d7b8eb/test/toxcore/methods.c#L79)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> 2 space indent.
</details>
Done.

---

*[test/toxcore/methods.c, line 182 \[r4\]](https://reviewable.io:443/reviews/toktok/hstox/14#-KMJmWtHRnf9T_yb-DRB:-KMJo4CPWYq6UgQebYLC:-499146009) ([raw file](https://github.com/toktok/hstox/blob/24aae626aac9ed66ad8f211579c5cef948d7b8eb/test/toxcore/methods.c#L182)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> Why is there an additional empty line here?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/14)*

**Comment by piling** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[test/toxcore/methods.c, line 57 \[r4\]](https://reviewable.io:443/reviews/toktok/hstox/14#-KMJlpyJcgfF-FCiVYek:-KMK-bzM65i9n7xGS8cp:-499146009) ([raw file](https://github.com/toktok/hstox/blob/24aae626aac9ed66ad8f211579c5cef948d7b8eb/test/toxcore/methods.c#L57)):*
<details><summary><i>Previously, piling wrote…</i></summary>
> Done.
</details>
Done.

---

*[test/toxcore/methods.c, line 68 \[r4\]](https://reviewable.io:443/reviews/toktok/hstox/14#-KMJliw2Xt919OAWkwwF:-KMK-Z6zjOMmIigNp3Rq:-499146009) ([raw file](https://github.com/toktok/hstox/blob/24aae626aac9ed66ad8f211579c5cef948d7b8eb/test/toxcore/methods.c#L68)):*
<details><summary><i>Previously, piling wrote…</i></summary>
> Done.
</details>
Done.

---

*[test/toxcore/methods.c, line 79 \[r4\]](https://reviewable.io:443/reviews/toktok/hstox/14#-KMJm0h3oASjfa0iUU3b:-KMK-a4kL0kxBD8TZVag:-499146009) ([raw file](https://github.com/toktok/hstox/blob/24aae626aac9ed66ad8f211579c5cef948d7b8eb/test/toxcore/methods.c#L79)):*
<details><summary><i>Previously, piling wrote…</i></summary>
> Done.
</details>
Done.

---

*[test/toxcore/methods.c, line 182 \[r4\]](https://reviewable.io:443/reviews/toktok/hstox/14#-KMJmWtHRnf9T_yb-DRB:-KMK-b1AgapAPVcrkuuy:-499146009) ([raw file](https://github.com/toktok/hstox/blob/24aae626aac9ed66ad8f211579c5cef948d7b8eb/test/toxcore/methods.c#L182)):*
<details><summary><i>Previously, piling wrote…</i></summary>
> Done.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/14)*

**Comment by iphydf** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[test/toxcore/methods.c, line 76 \[r6\]](https://reviewable.io:443/reviews/toktok/hstox/14#-KMKT-qXsJO34UKVqLw9:-KMKT-qY3tOb0LRsg-oK:145673979) ([raw file](https://github.com/toktok/hstox/blob/bf0ef28dbdd3607c7de06cf439abea3d34ffc69c/test/toxcore/methods.c#L76)):*
> ```C
> 
>   encrypt_precompute ((uint8_t *) args.ptr[1].via.bin.ptr,
>                         (uint8_t *) args.ptr[0].via.bin.ptr, combined_key);
> ```

Remove extra indent.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/14)*

**Comment by piling** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/toxcore/methods.c, line 76 \[r6\]](https://reviewable.io:443/reviews/toktok/hstox/14#-KMKT-qXsJO34UKVqLw9:-KMKmUizuhY6xwbw2pEZ:-499146009) ([raw file](https://github.com/toktok/hstox/blob/bf0ef28dbdd3607c7de06cf439abea3d34ffc69c/test/toxcore/methods.c#L76)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> Remove extra indent.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/14)*

**Comment by iphydf** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/14)*

**Comment by iphydf** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[test/toxcore/methods.c, line 16 \[r7\]](https://reviewable.io:443/reviews/toktok/hstox/14#-KMYdJDwRJ5O2Rgd0qeR:-KMYdJDwRJ5O2Rgd0qeS:-719355451) ([raw file](https://github.com/toktok/hstox/blob/4654fe209d4a37a63bc04421a65dfc8b5b59b311/test/toxcore/methods.c#L16)):*
> ```C
>   CHECK (args.size == 3);
>   CHECK (args.ptr[0].type == MSGPACK_OBJECT_BIN);
>   CHECK (args.ptr[0].via.bin.size == crypto_box_BEFORENMBYTES);
> ```

I think it actually makes sense to do: `msgpack_object_bin combined_key = args.ptr[0].via.bin`. It does not make sense to memcpy them into an array, but it does add to clarity to give the elements of args names.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/14)*

**Comment by iphydf** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[test/toxcore/methods.c, line 14 \[r7\]](https://reviewable.io:443/reviews/toktok/hstox/14#-KMYdcIRuvN3oCHfLOS5:-KMYdcIS4hAQ04tAnLMd:-333150226) ([raw file](https://github.com/toktok/hstox/blob/4654fe209d4a37a63bc04421a65dfc8b5b59b311/test/toxcore/methods.c#L14)):*
> ```C
> METHOD (array, Box, encrypt)
> {
>   CHECK (args.size == 3);
> ```

#34  adds CHECK_SIZE and CHECK_TYPE. You can use them here to get better error messages.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/14)*

**Comment by piling** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/toxcore/methods.c, line 14 \[r7\]](https://reviewable.io:443/reviews/toktok/hstox/14#-KMYdcIRuvN3oCHfLOS5:-KM_g6SMJQf9sjmjTuoJ:-499146009) ([raw file](https://github.com/toktok/hstox/blob/4654fe209d4a37a63bc04421a65dfc8b5b59b311/test/toxcore/methods.c#L14)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> #34  adds CHECK_SIZE and CHECK_TYPE. You can use them here to get better error messages.
</details>
Done.

---

*[test/toxcore/methods.c, line 16 \[r7\]](https://reviewable.io:443/reviews/toktok/hstox/14#-KMYdJDwRJ5O2Rgd0qeR:-KM_g8ytuWVwaqVUq_Id:-499146009) ([raw file](https://github.com/toktok/hstox/blob/4654fe209d4a37a63bc04421a65dfc8b5b59b311/test/toxcore/methods.c#L16)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> I think it actually makes sense to do: `msgpack_object_bin combined_key = args.ptr[0].via.bin`. It does not make sense to memcpy them into an array, but it does add to clarity to give the elements of args names.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/14)*

**Comment by iphydf** [comment]
Please open a new PR with updated code. Something went wrong with travis here.

**Pull request closed without merging**
