### PR TITLE
Add support for test flavours to the main Makefile.

### PR DESCRIPTION
**Pull request by iphydf**
This is needed for TokTok/toxcore#4.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/hstox/24)

### CODE REVIEW

**Comment by GrayHatter** [comment]
Reviewed 1 of 5 files at r1, 1 of 2 files at r2.
Review status: 2 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[Makefile, line 17 \[r3\]](https://reviewable.io:443/reviews/toktok/hstox/24#-KMG39TbxlzMRYsilsTR:-KMG39TcZ1IpbHyjWDCn:-1320530583) ([raw file](https://github.com/toktok/hstox/blob/16a9a0039cbde6f6f00eca2018731da4f1ef3c23/Makefile#L17)):*
> ```Makefile
> 
> # Test flavour. See test/toxcore/Makefile for choices.
> TEST	:= vanilla
> ```

if flavor is only for toxcore, shouldn't this have a different name?

---

*[Makefile, line 32 \[r3\]](https://reviewable.io:443/reviews/toktok/hstox/24#-KMG3If29WRfCMd1V1vz:-KMG3If29WRfCMd1V1w-:-164527923) ([raw file](https://github.com/toktok/hstox/blob/16a9a0039cbde6f6f00eca2018731da4f1ef3c23/Makefile#L32)):*
> ```Makefile
> 	--extra-lib-dirs=$(HOME)/.cabal/extra-dist/lib
> 
> all: check $(DOCS)
> ```

why $(DOCS)

---

*[Makefile, line 36 \[r3\]](https://reviewable.io:443/reviews/toktok/hstox/24#-KMG4VlaLboNSJouPXPs:-KMG4VlaLboNSJouPXPt:-2116256070) ([raw file](https://github.com/toktok/hstox/blob/16a9a0039cbde6f6f00eca2018731da4f1ef3c23/Makefile#L36)):*
> ```Makefile
> check: dist/hpc/tix/hstox/hstox.tix
> 	hpc markup $(HPC_DIRS) --destdir=dist/hpc/html $< > /dev/null
> 	hpc report $(HPC_DIRS) $<
> ```

BTW this seems to be leaving artifacts on my command line

e.g. ;2;1;22 

---

*[test/toxcore/.gitignore, line 2 \[r3\]](https://reviewable.io:443/reviews/toktok/hstox/24#-KMG3OT8PFjjsjYNFU2Z:-KMG3OT8PFjjsjYNFU2_:-1184236682) ([raw file](https://github.com/toktok/hstox/blob/886eecdf305c7b884d90e0f9c3d3ea5d53a28a02/test/toxcore/.gitignore#L2)):*
> ```
> /*.dSYM
> /*_main
> ```

Was this removed in a bad merge?

---

*[test/toxcore/Makefile, line 2 \[r3\]](https://reviewable.io:443/reviews/toktok/hstox/24#-KMG4MXWXFwFsGxBMM9T:-KMG4MXXKf6Kk93TOE_B:218155697) ([raw file](https://github.com/toktok/hstox/blob/16a9a0039cbde6f6f00eca2018731da4f1ef3c23/test/toxcore/Makefile#L2)):*
> ```Makefile
> CFLAGS	:=					\
> 	-std=gnu99				\
> ```

this may break my system, testing now, standby

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/24)*

**Comment by GrayHatter** [comment]
Review status: 2 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[Makefile, line 36 \[r3\]](https://reviewable.io:443/reviews/toktok/hstox/24#-KMG4VlaLboNSJouPXPs:-KMG4tzTJI9EGH9Ig5Ds:1067454496) ([raw file](https://github.com/toktok/hstox/blob/16a9a0039cbde6f6f00eca2018731da4f1ef3c23/Makefile#L36)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> BTW this seems to be leaving artifacts on my command line
> 
> e.g. ;2;1;22 
</details>
literal "1;2c1;2c"

---

*[test/toxcore/Makefile, line 2 \[r3\]](https://reviewable.io:443/reviews/toktok/hstox/24#-KMG4MXWXFwFsGxBMM9T:-KMG4n_HtYUJtsQE2Ib4:676834233) ([raw file](https://github.com/toktok/hstox/blob/16a9a0039cbde6f6f00eca2018731da4f1ef3c23/test/toxcore/Makefile#L2)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> this may break my system, testing now, standby
</details>
LGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/24)*

**Comment by iphydf** [comment]
Review status: 2 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[Makefile, line 17 \[r3\]](https://reviewable.io:443/reviews/toktok/hstox/24#-KMG39TbxlzMRYsilsTR:-KMG4ojoDNBdBmzmZqUU:-1056239051) ([raw file](https://github.com/toktok/hstox/blob/16a9a0039cbde6f6f00eca2018731da4f1ef3c23/Makefile#L17)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> if flavor is only for toxcore, shouldn't this have a different name?
</details>
It's not just for toxcore, but also for toxcore. The intention is that users who want to check coverage at home can do so as well. Or asan, if they like.

---

*[test/toxcore/.gitignore, line 2 \[r3\]](https://reviewable.io:443/reviews/toktok/hstox/24#-KMG3OT8PFjjsjYNFU2Z:-KMG4zgGonU_bDTd_cH2:-1775835516) ([raw file](https://github.com/toktok/hstox/blob/886eecdf305c7b884d90e0f9c3d3ea5d53a28a02/test/toxcore/.gitignore#L2)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> Was this removed in a bad merge?
</details>
No, it's no longer built, so it's no longer ignored.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/24)*

**Comment by GrayHatter** [comment]
Reviewed 2 of 5 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[Makefile, line 32 \[r3\]](https://reviewable.io:443/reviews/toktok/hstox/24#-KMG3If29WRfCMd1V1vz:-KMG5PfIW0yPXfAPYL3u:676834233) ([raw file](https://github.com/toktok/hstox/blob/16a9a0039cbde6f6f00eca2018731da4f1ef3c23/Makefile#L32)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> why $(DOCS)
</details>
LGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/24)*

**Comment by iphydf** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[Makefile, line 36 \[r3\]](https://reviewable.io:443/reviews/toktok/hstox/24#-KMG4VlaLboNSJouPXPs:-KMG5d_ZFZaKeqS7x_q3:-308238164) ([raw file](https://github.com/toktok/hstox/blob/16a9a0039cbde6f6f00eca2018731da4f1ef3c23/Makefile#L36)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> literal "1;2c1;2c"
</details>
No, that's msgpack-c being broken. Fixed in https://github.com/msgpack/msgpack-c/pull/497.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/24)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/24#-:-KMG5sdWEpah47M8J4ac:1417088721)*

**Pull request merged**
