### PR TITLE
Fixes to build on Arch linux

### PR DESCRIPTION
**Pull request by GrayHatter**
changes suggested by @iphydf to get `make` to work on my Arch box

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/hstox/21)

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/TokTok/hstox/pull/21%23issuecomment-231494333%22%2C%20%22https%3A//github.com/TokTok/hstox/pull/21%23issuecomment-231495202%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/TokTok/hstox/pull/21%23issuecomment-231494333%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%5B%21%5BCLA%20assistant%20check%5D%28https%3A//cla-assistant.io/pull/badge/signed%29%5D%28https%3A//cla-assistant.io/TokTok/hstox%3FpullRequest%3D21%29%20%3Cbr/%3EAll%20committers%20have%20signed%20the%20CLA.%22%2C%20%22created_at%22%3A%20%222016-07-08T23%3A15%3A05Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/11571300%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/CLAassistant%22%7D%7D%2C%20%7B%22body%22%3A%20%22also%20includes%20pr/20%22%2C%20%22created_at%22%3A%20%222016-07-08T23%3A22%3A07Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/243408%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/GrayHatter%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/TokTok/hstox/pull/21#issuecomment-231494333'>General Comment</a></b>
- <a href='https://github.com/CLAassistant'></a> [CLA assistant check](https://cla-assistant.io/TokTok/hstox?pullRequest=21) <br/>All committers have signed the CLA.
- <a href='https://github.com/GrayHatter'></a> also includes pr/20

<a href='https://www.codereviewhub.com/TokTok/hstox/pull/21?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/TokTok/hstox/pull/21?approve=1'></a>&nbsp;<a href='https://github.com/TokTok/hstox/pull/21'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by GrayHatter** [comment]
also includes pr/20

**Comment by GrayHatter** [comment]
@iphydf you closed #20, do you want to close this as well?

**Comment by iphydf** [comment]
I haven't looked at this, but there may be things to fix after merging #23. You can use this PR for those new changes.

**Comment by GrayHatter** [comment]
already fixed in master

**Pull request closed without merging**
