### PR TITLE
Add clang-format build step to check formatting on travis.

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/toktok/hstox/48)

### CODE REVIEW

**Comment by nbraud** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[.travis.yml, line 11 \[r1\]](https://reviewable.io:443/reviews/toktok/hstox/48#-KNqVHdDRge2-oEiQsC-:-KNqVHdDRge2-oEiQsC0:685814410) ([raw file](https://github.com/toktok/hstox/blob/7eaf61f18cceb941c6c4cd9a16540976a6a1ce41/.travis.yml#L11)):*
> ```YAML
>     packages:
>       - clang-format-3.8
>       - clang-tidy-3.8
> ```

Why `clang-tidy`?  Only `clang-format` is invoked.
Also, why not the version-independent `clang-format` virtual package? (assuming it is provided in `llvm-toolchain-precise-3.8`)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/48)*

**Comment by nbraud** [comment]
*[.travis.yml, line 8 \[r1\]](https://reviewable.io:443/reviews/toktok/hstox/48#-KNqXM0e_MonqpKYkkI0:-KNqXM0fwYA8Gheb_Dzq:521688706) ([raw file](https://github.com/toktok/hstox/blob/7eaf61f18cceb941c6c4cd9a16540976a6a1ce41/.travis.yml#L8)):*
> ```YAML
>     sources:
>       - llvm-toolchain-precise-3.8
>       - ubuntu-toolchain-r-test
> ```

There could be a comment explaining why that this is a PPA that contains a GCC backport, and that it is needed for the LLVM 3.8 tools on Precise (due to the `libstdc++` version)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/48)*

**Comment by iphydf** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[.travis.yml, line 8 \[r1\]](https://reviewable.io:443/reviews/toktok/hstox/48#-KNqXM0e_MonqpKYkkI0:-KNrLIJ6UF4jPI_qdkef:-499146009) ([raw file](https://github.com/toktok/hstox/blob/7eaf61f18cceb941c6c4cd9a16540976a6a1ce41/.travis.yml#L8)):*
<details><summary><i>Previously, nbraud (Nicolas Braud-Santoni) wrote…</i></summary>
> There could be a comment explaining why that this is a PPA that contains a GCC backport, and that it is needed for the LLVM 3.8 tools on Precise (due to the `libstdc++` version)
</details>
Done.

---

*[.travis.yml, line 11 \[r1\]](https://reviewable.io:443/reviews/toktok/hstox/48#-KNqVHdDRge2-oEiQsC-:-KNrLJ4cVy0iYcG6jGzt:-757724611) ([raw file](https://github.com/toktok/hstox/blob/7eaf61f18cceb941c6c4cd9a16540976a6a1ce41/.travis.yml#L11)):*
<details><summary><i>Previously, nbraud (Nicolas Braud-Santoni) wrote…</i></summary>
> Why `clang-tidy`?  Only `clang-format` is invoked.
> Also, why not the version-independent `clang-format` virtual package? (assuming it is provided in `llvm-toolchain-precise-3.8`)
</details>
It was WIP. I didn't know how to invoke clang-tidy yet, so I've added it now that I know.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/48)*

**Comment by iphydf** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[.travis.yml, line 8 \[r1\]](https://reviewable.io:443/reviews/toktok/hstox/48#-KNqXM0e_MonqpKYkkI0:-KNrVmFhUur7aSbA37XS:1347341358) ([raw file](https://github.com/toktok/hstox/blob/7eaf61f18cceb941c6c4cd9a16540976a6a1ce41/.travis.yml#L8)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> Done.
</details>
Error: `Disallowing packages: clang-format, clang-tidy`, so reverting back to the versioned packages. See https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise#L442-L451.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/48)*

**Comment by GrayHatter** [comment]
:lgtm: 

---

Reviewed 4 of 4 files at r2, 11 of 11 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/48#-:-KNpyd3OgX1CvPGKKOEX:980077423)*

**Comment by nbraud** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[.travis.yml, line 8 \[r1\]](https://reviewable.io:443/reviews/toktok/hstox/48#-KNqXM0e_MonqpKYkkI0:-KNxrpdsb7n8Z3w13KoZ:5173665) ([raw file](https://github.com/toktok/hstox/blob/7eaf61f18cceb941c6c4cd9a16540976a6a1ce41/.travis.yml#L8)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> Error: `Disallowing packages: clang-format, clang-tidy`, so reverting back to the versioned packages. See https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise#L442-L451.
</details>
OK

---

*[.travis.yml, line 11 \[r1\]](https://reviewable.io:443/reviews/toktok/hstox/48#-KNqVHdDRge2-oEiQsC-:-KNxrsRzJdqoXAqu6ANR:1826468475) ([raw file](https://github.com/toktok/hstox/blob/7eaf61f18cceb941c6c4cd9a16540976a6a1ce41/.travis.yml#L11)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> It was WIP. I didn't know how to invoke clang-tidy yet, so I've added it now that I know.
</details>
Great, thanks :-)

---

*[configure.mk, line 34 \[r3\]](https://reviewable.io:443/reviews/toktok/hstox/48#-KNxs7aK9MmV26T3oRzd:-KNxs7aK9MmV26T3oRze:-200375749) ([raw file](https://github.com/toktok/hstox/blob/5a94d79e7c057b8c256046ccadba6d56a8e78cc5/configure.mk#L34)):*
> ```Makefile
> CLANG_TIDY := clang-tidy
> endif
> ifneq ($(shell which clang_tidy),)
> ```

Why it this repeated?

---

*[configure.mk, line 37 \[r3\]](https://reviewable.io:443/reviews/toktok/hstox/48#-KNxs2UDr17WegS5tmsa:-KNxs2UDr17WegS5tmsb:-1756738732) ([raw file](https://github.com/toktok/hstox/blob/5a94d79e7c057b8c256046ccadba6d56a8e78cc5/configure.mk#L37)):*
> ```Makefile
> CLANG_TIDY := clang_tidy
> endif
> ifneq ($(shell which clang-tidy-4.9),)
> ```

Shouldn't that be `clang-tidy-3.8`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/48)*

**Comment by iphydf** [comment]
Review status: 14 of 15 files reviewed at latest revision, 3 unresolved discussions.

---

*[configure.mk, line 34 \[r3\]](https://reviewable.io:443/reviews/toktok/hstox/48#-KNxs7aK9MmV26T3oRzd:-KNyVSS0TutPmAbgDBDK:1843714511) ([raw file](https://github.com/toktok/hstox/blob/5a94d79e7c057b8c256046ccadba6d56a8e78cc5/configure.mk#L34)):*
<details><summary><i>Previously, nbraud (Nicolas Braud-Santoni) wrote…</i></summary>
> Why it this repeated?
</details>
It's not - one is clang-tidy, another is clang_tidy.

---

*[configure.mk, line 37 \[r3\]](https://reviewable.io:443/reviews/toktok/hstox/48#-KNxs2UDr17WegS5tmsa:-KNyVXw_Z4Cpi8po4C0O:-499146009) ([raw file](https://github.com/toktok/hstox/blob/5a94d79e7c057b8c256046ccadba6d56a8e78cc5/configure.mk#L37)):*
<details><summary><i>Previously, nbraud (Nicolas Braud-Santoni) wrote…</i></summary>
> Shouldn't that be `clang-tidy-3.8`?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/48)*

**Comment by nbraud** [comment]
Review status: 14 of 15 files reviewed at latest revision, 3 unresolved discussions.

---

*[configure.mk, line 34 \[r3\]](https://reviewable.io:443/reviews/toktok/hstox/48#-KNxs7aK9MmV26T3oRzd:-KNyhBW4q5vFb8yBFG51:1461765252) ([raw file](https://github.com/toktok/hstox/blob/5a94d79e7c057b8c256046ccadba6d56a8e78cc5/configure.mk#L34)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> It's not - one is clang-tidy, another is clang_tidy.
</details>
Indeed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/48)*

**Comment by nbraud** [comment]
Reviewed 3 of 4 files at r2, 11 of 11 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/48)*

**Comment by nbraud** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/48#-:-KNyhQR9t5OoW92AbCXI:1417088721)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/48#-:-KO-BRCVi_YjQuh-oz2W:1417088721)*

**Pull request merged**
