### PR TITLE
Add coverage builds for toxcore test binary.

### PR DESCRIPTION
**Pull request by iphydf**
The main function for test-toxcore is now no longer in Haskell, because ghc does
weird things[1] when compiling C code. Instead, we build it with a simple
Makefile in the test/toxcore directory, with main() in C.

[1] It outputs assembly into a temporary directory with the file named ghc_1.s.
    This means the gcno file required for coverage analysis is also there. named
    ghc_1.gcno. We can't get hold of it anymore, so any analysis goes into the
    temporary directory and likely fails. We could instead build libtoxcore with
    coverage and install it somewhere, but it's not worth the effort.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/hstox/23)

### CODE REVIEW

**Comment by GrayHatter** [comment]
Reviewed 8 of 10 files at r1.
Review status: 8 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/toxcore/libsodium, line 1 \[r1\]](https://reviewable.io:443/reviews/toktok/hstox/23#-KMFZGl6KCvMDPfJmqcv:-KMFZGl76NB9JxuCH6Tu:-987296114) ([raw file](https://github.com/toktok/hstox/blob/5e8abd618b0eef26dd5bfabd086e3715b0f171da/test/toxcore/libsodium#L1)):*
> ```
> Subproject commit f01d7c128214e8f976889c8093a42d9cae1abe4b
> ```

This change isn't documented anywhere. No From version, no To version

---

*[test/toxcore/test_main, line 0 \[r1\]](https://reviewable.io:443/reviews/toktok/hstox/23#-KMFZuY2_CN_Lpmc8RE4:-KMFZuY3zJqYOB56xPLu:-142427048) ([raw file](https://github.com/toktok/hstox/blob/5e8abd618b0eef26dd5bfabd086e3715b0f171da/test/toxcore/test_main#L0)):*
Do we really want to commit a bin?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/23)*

**Comment by iphydf** [comment]
Review status: 4 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/toxcore/libsodium, line 1 \[r1\]](https://reviewable.io:443/reviews/toktok/hstox/23#-KMFZGl6KCvMDPfJmqcv:-KMFe0P8AbC6dEqx-Rxn:406890099) ([raw file](https://github.com/toktok/hstox/blob/5e8abd618b0eef26dd5bfabd086e3715b0f171da/test/toxcore/libsodium#L1)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> This change isn't documented anywhere. No From version, no To version
</details>
It's changing to the "stable" branch. I think it was on some master before, which is bad.

---

*[test/toxcore/test_main, line  \[r1\]](https://reviewable.io:443/reviews/toktok/hstox/23#-KMFZuY2_CN_Lpmc8RE4:-KMFe57Wer1E85sXhxUQ:1152740957) ([raw file](https://github.com/toktok/hstox/blob/5e8abd618b0eef26dd5bfabd086e3715b0f171da/test/toxcore/test_main#L)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> Do we really want to commit a bin?
</details>
Nope. Added these to .gitignore.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/23)*

**Comment by GrayHatter** [comment]
Reviewed 1 of 10 files at r1, 6 of 7 files at r2.
Review status: 10 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/toxcore/test_main.c, line 34 \[r2\]](https://reviewable.io:443/reviews/toktok/hstox/23#-KMFfFY_1HxjeFWMtsjE:-KMFfFY_1HxjeFWMtsjF:1306773076) ([raw file](https://github.com/toktok/hstox/blob/2348e32c42b508349a7fb5952be3d0a2f0879e10/test/toxcore/test_main.c#L34)):*
> ```C
> {
>   struct settings cfg = { true, true };
>   uint32_t result = network_main (cfg, 1234);
> ```

How do you feel about magic numbers?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/23)*

**Comment by iphydf** [comment]
Review status: 10 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/toxcore/test_main.c, line 34 \[r2\]](https://reviewable.io:443/reviews/toktok/hstox/23#-KMFfFY_1HxjeFWMtsjE:-KMFfoxJtQxvMIe_Uqjp:-499146009) ([raw file](https://github.com/toktok/hstox/blob/2348e32c42b508349a7fb5952be3d0a2f0879e10/test/toxcore/test_main.c#L34)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> How do you feel about magic numbers?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/23)*

**Comment by GrayHatter** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/23#-:-KMFg-7btlvBCIQIurQ2:1417088721)*

**Pull request merged**
