### PR TITLE
CipherText Encode and decode

### PR DESCRIPTION
**Pull request by GrayHatter**
This change is [Reviewable](https://reviewable.io/reviews/toktok/hstox/52)

### CODE REVIEW

**Comment by iphydf** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[test/toxcore/binary_decode.c, line 7 \[r1\]](https://reviewable.io:443/reviews/toktok/hstox/52#-KO-U53GkpsDbnKS6VTJ:-KO-U53GkpsDbnKS6VTK:1874556225) ([raw file](https://github.com/toktok/hstox/blob/84459b46c9528da2679feeeda22eea6140df38e6/test/toxcore/binary_decode.c#L7)):*
> ```C
> METHOD(bin, Binary_decode, CipherText) {
>   uint64_t size = args.size;
>   uint64_t length = 0;
> ```

Don't initialise. In general, it might be good defensive coding style, but in these tests, please avoid it. It's a bug for length to be its initial value when being read later on. You could avoid the mess by putting the memcpy/be64toh into the SUCCESS block.

---

*[test/toxcore/binary_decode.c, line 18 \[r1\]](https://reviewable.io:443/reviews/toktok/hstox/52#-KO-UULJk_BKOptuOHbE:-KO-UULJk_BKOptuOHbF:-563705648) ([raw file](https://github.com/toktok/hstox/blob/84459b46c9528da2679feeeda22eea6140df38e6/test/toxcore/binary_decode.c#L18)):*
> ```C
>     if (size >= sizeof(uint64_t) && size == length + sizeof(uint64_t)) {
>       msgpack_pack_bin(res, args.size - sizeof(uint64_t));
>       msgpack_pack_bin_body(res, (args.ptr + sizeof(uint64_t)),
> ```

Remove () around second argument.

---

*[test/toxcore/binary_encode.c, line 9 \[r1\]](https://reviewable.io:443/reviews/toktok/hstox/52#-KO-UXxcsu5ger_DiFXw:-KO-UXxcsu5ger_DiFXx:-490917357) ([raw file](https://github.com/toktok/hstox/blob/84459b46c9528da2679feeeda22eea6140df38e6/test/toxcore/binary_encode.c#L9)):*
> ```C
> 
>   SUCCESS {
>     msgpack_pack_bin(res, sizeof(length) + args.size);
> ```

Remove () around length. Perhaps replace it with uint64_t (keeping the ()) for consistency with the corresponding decode function. Up to you to choose, but then be consistent.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/52)*

**Comment by iphydf** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[test/toxcore/binary_decode.c, line 12 \[r1\]](https://reviewable.io:443/reviews/toktok/hstox/52#-KO-Uqwb_G8j6_RGvb7n:-KO-Uqwb_G8j6_RGvb7o:1488641347) ([raw file](https://github.com/toktok/hstox/blob/84459b46c9528da2679feeeda22eea6140df38e6/test/toxcore/binary_decode.c#L12)):*
> ```C
>   if (size >= sizeof(uint64_t)) {
>     memcpy(&tmp, args.ptr, sizeof(uint64_t));
>     length = be64toh(tmp);
> ```

Does toxcore have this function? Perhaps you can use it here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/52)*

**Comment by GrayHatter** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[test/toxcore/binary_decode.c, line 7 \[r1\]](https://reviewable.io:443/reviews/toktok/hstox/52#-KO-U53GkpsDbnKS6VTJ:-KO-V1-5JJ7qNyz9OHjx:-836684462) ([raw file](https://github.com/toktok/hstox/blob/84459b46c9528da2679feeeda22eea6140df38e6/test/toxcore/binary_decode.c#L7)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> Don't initialise. In general, it might be good defensive coding style, but in these tests, please avoid it. It's a bug for length to be its initial value when being read later on. You could avoid the mess by putting the memcpy/be64toh into the SUCCESS block.
</details>
sorry, wrote this code before the last time you asked

Done

---

*[test/toxcore/binary_decode.c, line 12 \[r1\]](https://reviewable.io:443/reviews/toktok/hstox/52#-KO-Uqwb_G8j6_RGvb7n:-KO-WgJTsvfWCEY0G8YN:1982661002) ([raw file](https://github.com/toktok/hstox/blob/84459b46c9528da2679feeeda22eea6140df38e6/test/toxcore/binary_decode.c#L12)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> Does toxcore have this function? Perhaps you can use it here.
</details>
It has a host_to_net fxn, but as it's coming in, in 'net endian' this is to help out msgpack.

---

*[test/toxcore/binary_decode.c, line 18 \[r1\]](https://reviewable.io:443/reviews/toktok/hstox/52#-KO-UULJk_BKOptuOHbE:-KO-WF7BcT5lPfjgQ3_j:-499146009) ([raw file](https://github.com/toktok/hstox/blob/84459b46c9528da2679feeeda22eea6140df38e6/test/toxcore/binary_decode.c#L18)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> Remove () around second argument.
</details>
Done.

---

*[test/toxcore/binary_encode.c, line 9 \[r1\]](https://reviewable.io:443/reviews/toktok/hstox/52#-KO-UXxcsu5ger_DiFXw:-KO-WVGVQ1wnWikLJFre:-499146009) ([raw file](https://github.com/toktok/hstox/blob/84459b46c9528da2679feeeda22eea6140df38e6/test/toxcore/binary_encode.c#L9)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> Remove () around length. Perhaps replace it with uint64_t (keeping the ()) for consistency with the corresponding decode function. Up to you to choose, but then be consistent.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/52)*

**Comment by iphydf** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/52#-:-KO0-WXl34eDkLVsbvi1:1417088721)*

**Comment by iphydf** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/52)*

**Pull request merged**
