### PR TITLE
Bin En/Decode NodeInfo

### PR DESCRIPTION
**Pull request by GrayHatter**
This change is [Reviewable](https://reviewable.io/reviews/toktok/hstox/38)

### CODE REVIEW

**Comment by GrayHatter** [comment]
Binary Encode/Decode for NodeInfo passes

**Comment by GrayHatter** [comment]
Will squash and rebase after #37 get's merged

**Comment by GrayHatter** [comment]
Squashed, ready to merge

**Comment by iphydf** [comment]
Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[test/toxcore/binary_decode.c, line 31 \[r6\]](https://reviewable.io:443/reviews/toktok/hstox/38#-KNkt6Ifm-F93xrVSPVv:-KNkt6Ifm-F93xrVSPVw:-820401434) ([raw file](https://github.com/toktok/hstox/blob/70d7a5dae7eaa4be9141b479981399dcf5e19a27/test/toxcore/binary_decode.c#L31)):*
> ```C
> METHOD (bin, Binary_decode, NodeInfo)
> {
>   uint16_t data_processed = 0;
> ```

Don't initialise (you don't initialise `node` either). If unpack_nodes doesn't initialise this (does it sometimes not?), that's a bug we'd like to catch with asan or other tools.

---

*[test/toxcore/binary_decode.c, line 33 \[r6\]](https://reviewable.io:443/reviews/toktok/hstox/38#-KNkt0bceu02A24krVux:-KNkt0bceu02A24krVuy:690246203) ([raw file](https://github.com/toktok/hstox/blob/70d7a5dae7eaa4be9141b479981399dcf5e19a27/test/toxcore/binary_decode.c#L33)):*
> ```C
>   uint16_t data_processed = 0;
>   Node_format node;
>   int len = unpack_nodes(&node, 1, &data_processed, (const uint8_t*)args.ptr, args.size, 1);
> ```

`uint8_t const *`

---

*[test/toxcore/binary_decode.c, line 35 \[r6\]](https://reviewable.io:443/reviews/toktok/hstox/38#-KNku7dNlFcJF9pwmjaX:-KNku7dNlFcJF9pwmjaY:-467760051) ([raw file](https://github.com/toktok/hstox/blob/70d7a5dae7eaa4be9141b479981399dcf5e19a27/test/toxcore/binary_decode.c#L35)):*
> ```C
>   int len = unpack_nodes(&node, 1, &data_processed, (const uint8_t*)args.ptr, args.size, 1);
> 
>   bool ip6_node = ((node.ip_port.ip.family == AF_INET6) || (node.ip_port.ip.family == TCP_INET6));
> ```

Remove all () here and on the next line.

---

*[test/toxcore/binary_decode.c, line 48 \[r6\]](https://reviewable.io:443/reviews/toktok/hstox/38#-KNksfz2bkbUxAkLDq2d:-KNksfz2bkbUxAkLDq2e:1700314491) ([raw file](https://github.com/toktok/hstox/blob/70d7a5dae7eaa4be9141b479981399dcf5e19a27/test/toxcore/binary_decode.c#L48)):*
> ```C
>     SUCCESS {
>       msgpack_pack_array(res, 3);
>         msgpack_pack_uint8(res, tcp);
> ```

This indentation is going to be killed if/when we get an automatic formatter. Consider using {} to make the grouping.

---

*[test/toxcore/binary_encode.c, line 107 \[r6\]](https://reviewable.io:443/reviews/toktok/hstox/38#-KNkuGOz-wPqbATg7aH3:-KNkuGOz-wPqbATg7aH4:1643555682) ([raw file](https://github.com/toktok/hstox/blob/70d7a5dae7eaa4be9141b479981399dcf5e19a27/test/toxcore/binary_encode.c#L107)):*
> ```C
>   memcpy(&node.public_key, public_key.ptr, crypto_box_PUBLICKEYBYTES);
> 
>   uint8_t packed_node[PACKED_NODE_SIZE_IP6] = {0}; /* We assume IP6 because it's bigger */
> ```

Don't initialise.

---

*[test/toxcore/binary_encode.c, line 109 \[r6\]](https://reviewable.io:443/reviews/toktok/hstox/38#-KNkuTGpGeoQPQ_gtiy5:-KNkuTGq-oGzm_IKo06e:1528411407) ([raw file](https://github.com/toktok/hstox/blob/70d7a5dae7eaa4be9141b479981399dcf5e19a27/test/toxcore/binary_encode.c#L109)):*
> ```C
>   uint8_t packed_node[PACKED_NODE_SIZE_IP6] = {0}; /* We assume IP6 because it's bigger */
> 
>   int len = pack_nodes(packed_node, sizeof(Node_format), &node, 1);
> ```

`/* Pack number of nodes into data of maxlength length.`

Instead of `sizeof(Node_format)`, use `sizeof packed_node`.

---

*[test/toxcore/binary_encode.c, line 111 \[r6\]](https://reviewable.io:443/reviews/toktok/hstox/38#-KNkucK5zUJz-WpBbec9:-KNkucK5zUJz-WpBbecA:-1123979285) ([raw file](https://github.com/toktok/hstox/blob/70d7a5dae7eaa4be9141b479981399dcf5e19a27/test/toxcore/binary_encode.c#L111)):*
> ```C
>   int len = pack_nodes(packed_node, sizeof(Node_format), &node, 1);
> 
>   CHECK (len > 0);
> ```

Remove this line. If it's 0, there will be a 0-length bin as a return value, and the test runner will notice. Adding a branch here makes the fuzzer's life harder.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/38)*

**Comment by GrayHatter** [comment]
Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[test/toxcore/binary_decode.c, line 31 \[r6\]](https://reviewable.io:443/reviews/toktok/hstox/38#-KNkt6Ifm-F93xrVSPVv:-KNpjHMiBuw911XDcTAd:1239463576) ([raw file](https://github.com/toktok/hstox/blob/70d7a5dae7eaa4be9141b479981399dcf5e19a27/test/toxcore/binary_decode.c#L31)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> Don't initialise (you don't initialise `node` either). If unpack_nodes doesn't initialise this (does it sometimes not?), that's a bug we'd like to catch with asan or other tools.
</details>
It never does, but it's only outputting the size of the data it was able to unpack, and it's left untouched during error.

---

*[test/toxcore/binary_decode.c, line 33 \[r6\]](https://reviewable.io:443/reviews/toktok/hstox/38#-KNkt0bceu02A24krVux:-KNpke03k7qr96Ihwoz8:-499146009) ([raw file](https://github.com/toktok/hstox/blob/70d7a5dae7eaa4be9141b479981399dcf5e19a27/test/toxcore/binary_decode.c#L33)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> `uint8_t const *`
</details>
Done.

---

*[test/toxcore/binary_decode.c, line 35 \[r6\]](https://reviewable.io:443/reviews/toktok/hstox/38#-KNku7dNlFcJF9pwmjaX:-KNpkfePCeiPq_asq2-_:1637515936) ([raw file](https://github.com/toktok/hstox/blob/70d7a5dae7eaa4be9141b479981399dcf5e19a27/test/toxcore/binary_decode.c#L35)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> Remove all () here and on the next line.
</details>
Done. Why? (I added for clarity of reading thought.

---

*[test/toxcore/binary_decode.c, line 48 \[r6\]](https://reviewable.io:443/reviews/toktok/hstox/38#-KNksfz2bkbUxAkLDq2d:-KNpkxysFBtRTLgbarhM:1769759127) ([raw file](https://github.com/toktok/hstox/blob/70d7a5dae7eaa4be9141b479981399dcf5e19a27/test/toxcore/binary_decode.c#L48)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> This indentation is going to be killed if/when we get an automatic formatter. Consider using {} to make the grouping.
</details>
I'll just drop it flat, again it's only in here for readability.  I also changed the Order of the struct.

---

*[test/toxcore/binary_encode.c, line 107 \[r6\]](https://reviewable.io:443/reviews/toktok/hstox/38#-KNkuGOz-wPqbATg7aH3:-KNplfqqMOcZshMXmBXP:-499146009) ([raw file](https://github.com/toktok/hstox/blob/70d7a5dae7eaa4be9141b479981399dcf5e19a27/test/toxcore/binary_encode.c#L107)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> Don't initialise.
</details>
Done.

---

*[test/toxcore/binary_encode.c, line 109 \[r6\]](https://reviewable.io:443/reviews/toktok/hstox/38#-KNkuTGpGeoQPQ_gtiy5:-KNppK3MsGPJhPKk1QHv:-499146009) ([raw file](https://github.com/toktok/hstox/blob/70d7a5dae7eaa4be9141b479981399dcf5e19a27/test/toxcore/binary_encode.c#L109)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> `/* Pack number of nodes into data of maxlength length.`
> 
> Instead of `sizeof(Node_format)`, use `sizeof packed_node`.
</details>
Done.

---

*[test/toxcore/binary_encode.c, line 111 \[r6\]](https://reviewable.io:443/reviews/toktok/hstox/38#-KNkucK5zUJz-WpBbec9:-KNpmKhvwiWGDjBDD12T:-499146009) ([raw file](https://github.com/toktok/hstox/blob/70d7a5dae7eaa4be9141b479981399dcf5e19a27/test/toxcore/binary_encode.c#L111)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> Remove this line. If it's 0, there will be a 0-length bin as a return value, and the test runner will notice. Adding a branch here makes the fuzzer's life harder.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/38)*

**Comment by iphydf** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/toxcore/binary_decode.c, line 35 \[r6\]](https://reviewable.io:443/reviews/toktok/hstox/38#-KNku7dNlFcJF9pwmjaX:-KNpr8C3Rvi5VouZKAvH:-462161606) ([raw file](https://github.com/toktok/hstox/blob/70d7a5dae7eaa4be9141b479981399dcf5e19a27/test/toxcore/binary_decode.c#L35)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> Done. Why? (I added for clarity of reading thought.
</details>
In most cases, I think people should know operator precedence. In this case, I think people *really* should know operator precedence. In expressions involving || and && together, it's ok to put () around the && expression to clarify its higher precedence. In general, I like to avoid redundant syntax.

---

*[test/toxcore/binary_encode.c, line 109 \[r6\]](https://reviewable.io:443/reviews/toktok/hstox/38#-KNkuTGpGeoQPQ_gtiy5:-KNpuQKcRMO9NC5xupO4:-1764638915) ([raw file](https://github.com/toktok/hstox/blob/70d7a5dae7eaa4be9141b479981399dcf5e19a27/test/toxcore/binary_encode.c#L109)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>
> Done.
</details>
`sizeof packed_node` since `packed_node` is not a type.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/38)*

**Comment by iphydf** [comment]
Reviewed 1 of 3 files at r4, 1 of 2 files at r7, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/38)*

**Comment by GrayHatter** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/toxcore/binary_encode.c, line 109 \[r6\]](https://reviewable.io:443/reviews/toktok/hstox/38#-KNkuTGpGeoQPQ_gtiy5:-KNpwjiq2BMTObbQgBQ2:-499146009) ([raw file](https://github.com/toktok/hstox/blob/70d7a5dae7eaa4be9141b479981399dcf5e19a27/test/toxcore/binary_encode.c#L109)):*
<details><summary><i>Previously, iphydf wrote…</i></summary>
> `sizeof packed_node` since `packed_node` is not a type.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/38)*

**Comment by iphydf** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/38#-:-KNpwqQ5S6dAKTXh_DKZ:1417088721)*

**Comment by iphydf** [comment]
Reviewed 1 of 1 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/38)*

**Comment by iphydf** [comment]
Reviewed 2 of 2 files at r11.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hstox/38)*

**Pull request merged**
